### ISSUE TITLE
FindAccessedAddrsExegesisTest: can't run 'latency' mode

### ISSUE THREAD

**Issue by ronghongbo** [google/gematria#112]
Hello, after building gematria, there is 1 failure with FindAccessedAddrsExegesisTest:
```
(env)$ env USE_BAZEL_VERSION=6.4.0 ../bazelisk-linux-amd64 test ...
...
//gematria/datasets:find_accessed_addrs_exegesis_test                    FAILED in 0.8s
  /home/hrong1/.cache/bazel/_bazel_hrong1/32246067180bfaeac7e17e4449bcdc84/execroot/com_google_gematria/bazel-out/k8-fastbuild/testlogs/gematria/datasets/find_accessed_addrs_exegesis_test/test.log

Executed 1 out of 51 tests: 50 tests pass and 1 fails locally.
```
Here is the content of find_accessed_addrs_exegesis_test/test.log:
```
Executing tests from //gematria/datasets:find_accessed_addrs_exegesis_test
-----------------------------------------------------------------------------
Running main() from gmock_main.cc
[==========] Running 5 tests from 1 test suite.
[----------] Global test environment set-up.
[----------] 5 tests from FindAccessedAddrsExegesisTest
[ RUN      ] FindAccessedAddrsExegesisTest.ExegesisNoAccess
Failure value returned from cantFail wrapped call
can't run 'latency' mode, sched model does not define a cycle counter. You can pass --benchmark-phase=... to skip the actual benchmarking or --use-dummy-perf-counters to not query the kernel for real event counts.
UNREACHABLE executed at external/llvm-project/llvm/include/llvm/Support/Error.h:790!
```
Is this expected? This looks like an important test to fix, as it seems to measure cycles of instructions, which I guess is a basic functionality of gematria. 
Thanks!

**Comment by boomanaiden154** [comment]
What microarchitecture are you running on? The microarchitecture needs to be supported within `llvm-exegesis` on the LLVM side. It looks like whatever platform you're on isn't currently supported.

**Comment by ronghongbo** [comment]
I suppose to be using x86:
```
$ uname -a
Linux 5.15.146.1-microsoft-standard-WSL2 #1 SMP Thu Jan 11 04:09:03 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 22.04.4 LTS
Release:        22.04
Codename:       jammy
```

Is there any microarchitecture option that is needed to pass when using "bazel build" and "bazel test"? Or how to check which microarchitecture is actually used? Thanks!

**Comment by boomanaiden154** [comment]
The microarchitecture is automatically detected at runtime using the LLVM facilities. You don't need to pass anything into the build. Reporting the output of something like `llc --version` would be ideal. Something like `lscpu` will work too, although it will be a bit more "raw". If you have that, I can probably push a fix on the LLVM side (although might not be able to validate it).

**Comment by ronghongbo** [comment]
Sure. Here is the info:
```
$ llc --version
Ubuntu LLVM version 14.0.0

  Optimized build.
  Default target: x86_64-pc-linux-gnu
  Host CPU: alderlake

  Registered Targets:
    aarch64    - AArch64 (little endian)
    aarch64_32 - AArch64 (little endian ILP32)
    aarch64_be - AArch64 (big endian)
    amdgcn     - AMD GCN GPUs
    arm        - ARM
    arm64      - ARM64 (little endian)
    arm64_32   - ARM64 (little endian ILP32)
    armeb      - ARM (big endian)
    avr        - Atmel AVR Microcontroller
    bpf        - BPF (host endian)
    bpfeb      - BPF (big endian)
    bpfel      - BPF (little endian)
    hexagon    - Hexagon
    lanai      - Lanai
    m68k       - Motorola 68000 family
    mips       - MIPS (32-bit big endian)
    mips64     - MIPS (64-bit big endian)
    mips64el   - MIPS (64-bit little endian)
    mipsel     - MIPS (32-bit little endian)
    msp430     - MSP430 [experimental]
    nvptx      - NVIDIA PTX 32-bit
    nvptx64    - NVIDIA PTX 64-bit
    ppc32      - PowerPC 32
    ppc32le    - PowerPC 32 LE
    ppc64      - PowerPC 64
    ppc64le    - PowerPC 64 LE
    r600       - AMD GPUs HD2XXX-HD6XXX
    riscv32    - 32-bit RISC-V
    riscv64    - 64-bit RISC-V
    sparc      - Sparc
    sparcel    - Sparc LE
    sparcv9    - Sparc V9
    systemz    - SystemZ
    thumb      - Thumb
    thumbeb    - Thumb (big endian)
    ve         - VE
    wasm32     - WebAssembly 32-bit
    wasm64     - WebAssembly 64-bit
    x86        - 32-bit X86: Pentium-Pro and above
    x86-64     - 64-bit X86: EM64T and AMD64
    xcore      - XCore
```
Thanks!

**Comment by boomanaiden154** [comment]
https://github.com/llvm/llvm-project/pull/88967 should fix the issue.

**Comment by boomanaiden154** [comment]
Right. The llvm that gets used by the bazel build is in `./bazel-gematria/external/llvm-project`. It's not set up as a git repository though, so you'll probably have to download the patch and apply it manually.

**Comment by ronghongbo** [comment]
I patched the downloaded llvm with the above fix for adlerlake. Then rebuilt it. Then `ln -s $LLVM_PROJECT_SRC bazel-gematria/external/llvm-project` and rebuilt gematria as well. However, still run into the same two errors. Did I miss anything?

**Comment by boomanaiden154** [comment]
It works for me locally (or is at least able to find the scheduling model). I doubt Bazel is happy with you creating a symlink there and probably deletes the symlink. Have you checked that the changes are still applied after rebuilding? You probably need to apply the patch manually.

**Comment by ronghongbo** [comment]
Thanks for verifying the fix, Aiden. I still have the same issue with the patch, but I guess that is probably due to my local setting. Let’s drop this issue for now. If needed and time permitted, I may trace to see why.
